### ISSUE TITLE
Error after adding extension

### ISSUE THREAD

**Issue by ozgurctk** [sleeyax/burp-awesome-tls#43] opened 2023-11-22 22:51 UTC
When I added the extension I get this error.

java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Integer.parseInt(Integer.java:630)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at burp.Settings.getHttpTimeout(Settings.java:68)
	at burp.SettingsTab.<init>(SettingsTab.java:44)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:33)
	at burp.Zcuc.Zw(Unknown Source)
	at burp.Zsmc.ZS(Unknown Source)
	at burp.Zsmz.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Integer.parseInt(Integer.java:630)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at burp.Settings.getHttpTimeout(Settings.java:68)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:58)
	at burp.Znx2.handleHttpRequestToBeSent(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at burp.Zcnb.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy64.handleHttpRequestToBeSent(Unknown Source)
	at burp.Ziby.ZG(Unknown Source)
	at burp.Zsmr.ZG(Unknown Source)
	at burp.Zfft.ZG(Unknown Source)
	at burp.Zik3.Zv(Unknown Source)
	at burp.Zink.ZD(Unknown Source)
	at burp.Zink.ZH(Unknown Source)
	at burp.Zte5.ZH(Unknown Source)
	at burp.Ziot.ZH(Unknown Source)
	at burp.Zkeg.ZH(Unknown Source)
	at burp.Zcug.ZU(Unknown Source)
	at burp.Zkkj.ZC(Unknown Source)
	at burp.Zkk7.ZC(Unknown Source)
	at burp.Zfmk.ZJ(Unknown Source)
	at burp.Ztir.lambda$issueRequest$0(Unknown Source)
	at burp.Zcq9.ZR(Unknown Source)
	at burp.Zcv3.Zt(Unknown Source)
	at burp.Zcv3.Zw(Unknown Source)
	at burp.Zbns.Zb(Unknown Source)
	at burp.Ztre.Zb(Unknown Source)
	at burp.Ztir.Ze(Unknown Source)
	at burp.Zi8v.Zn(Unknown Source)
	at burp.Zg3y.ZG(Unknown Source)
	at burp.Zce3.Zi(Unknown Source)
	at burp.Zfld.Zb(Unknown Source)
	at burp.Zfld.Zp(Unknown Source)
	at burp.Zm7q.Zc(Unknown Source)
	at burp.Zpv.Zg(Unknown Source)
	at burp.Zk1b.ZZ(Unknown Source)
	at burp.Ziso.run(Unknown Source)
	at burp.Zcjg.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Integer.parseInt(Integer.java:630)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at burp.Settings.getHttpTimeout(Settings.java:68)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:58)
	at burp.Znx2.handleHttpRequestToBeSent(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at burp.Zcnb.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy64.handleHttpRequestToBeSent(Unknown Source)
	at burp.Ziby.ZG(Unknown Source)
	at burp.Zsmr.ZG(Unknown Source)
	at burp.Zfft.ZG(Unknown Source)
	at burp.Zik3.Zv(Unknown Source)
	at burp.Zink.ZD(Unknown Source)
	at burp.Zink.ZH(Unknown Source)
	at burp.Zte5.ZH(Unknown Source)
	at burp.Ziot.ZH(Unknown Source)
	at burp.Zkeg.ZH(Unknown Source)
	at burp.Zcug.ZU(Unknown Source)
	at burp.Zkkj.ZC(Unknown Source)
	at burp.Zkk7.ZC(Unknown Source)
	at burp.Zfmk.ZJ(Unknown Source)
	at burp.Ztir.lambda$issueRequest$0(Unknown Source)
	at burp.Zcq9.ZR(Unknown Source)
	at burp.Zcv3.Zt(Unknown Source)
	at burp.Zcv3.Zw(Unknown Source)
	at burp.Zbns.Zb(Unknown Source)
	at burp.Ztre.Zb(Unknown Source)
	at burp.Ztir.Ze(Unknown Source)
	at burp.Zi8v.Zn(Unknown Source)
	at burp.Zg3y.ZG(Unknown Source)
	at burp.Zce3.Zi(Unknown Source)
	at burp.Zfld.Zb(Unknown Source)
	at burp.Zfld.Zp(Unknown Source)
	at burp.Zm7q.Zc(Unknown Source)
	at burp.Zpv.Zg(Unknown Source)
	at burp.Zk1b.ZZ(Unknown Source)
	at burp.Ziso.run(Unknown Source)
	at burp.Zcjg.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Integer.parseInt(Integer.java:630)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at burp.Settings.getHttpTimeout(Settings.java:68)
	at burp.BurpExtender.processHttpMessage(BurpExtender.java:58)
	at burp.Znx2.handleHttpRequestToBeSent(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at burp.Zcnb.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy64.handleHttpRequestToBeSent(Unknown Source)
	at burp.Ziby.ZG(Unknown Source)
	at burp.Zsmr.ZG(Unknown Source)
	at burp.Zfft.ZG(Unknown Source)
	at burp.Zik3.Zv(Unknown Source)
	at burp.Zink.ZD(Unknown Source)
	at burp.Zink.ZH(Unknown Source)
	at burp.Zte5.ZH(Unknown Source)
	at burp.Ziot.ZH(Unknown Source)
	at burp.Zkeg.ZH(Unknown Source)
	at burp.Zcug.ZU(Unknown Source)
	at burp.Zkkj.ZC(Unknown Source)
	at burp.Zkk7.ZC(Unknown Source)
	at burp.Zfmk.ZJ(Unknown Source)
	at burp.Ztir.lambda$issueRequest$0(Unknown Source)
	at burp.Zcq9.ZR(Unknown Source)
	at burp.Zcv3.Zt(Unknown Source)
	at burp.Zcv3.Zw(Unknown Source)
	at burp.Zbns.Zb(Unknown Source)
	at burp.Ztre.Zb(Unknown Source)
	at burp.Ztir.Ze(Unknown Source)
	at burp.Zi8v.Zn(Unknown Source)
	at burp.Zg3y.ZG(Unknown Source)
	at burp.Zce3.Zi(Unknown Source)
	at burp.Zfld.Zb(Unknown Source)
	at burp.Zfld.Zp(Unknown Source)
	at burp.Zm7q.Zc(Unknown Source)
	at burp.Zpv.Zg(Unknown Source)
	at burp.Zk1b.ZZ(Unknown Source)
	at burp.Ziso.run(Unknown Source)
	at burp.Zcjg.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)

**Comment by sleeyax** [comment] 2023-11-23 00:00
Duplicate of: #15.

See https://github.com/sleeyax/burp-awesome-tls/issues/15#issuecomment-1575056463

**Closed** 2023-11-23 00:01 UTC
