### ISSUE TITLE
Not Worked

### ISSUE THREAD

**Issue by 0xmaximus** [sleeyax/burp-awesome-tls#21] opened 2022-11-10 15:34 UTC
java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Integer.parseInt(Integer.java:627)
	at java.base/java.lang.Integer.parseInt(Integer.java:781)
	at burp.Settings.getTimeout(Settings.java:52)
	at burp.SettingsTab.<init>(SettingsTab.java:38)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:33)
	at burp.zkf.K(Unknown Source)
	at burp.u2d.O(Unknown Source)
	at burp.u29.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)

**Comment by sleeyax** [comment] 2022-11-10 15:54
Duplicate of: #15 

Restart burp or reload the plugin as a work-around.

**Closed** 2022-11-10 15:55 UTC
