### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Sudo-Doxi** [sleeyax/burp-awesome-tls#52] opened 2023-12-21 07:04 UTC
java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Integer.parseInt(Integer.java:627)
	at java.base/java.lang.Integer.parseInt(Integer.java:781)
	at burp.Settings.getHttpTimeout(Settings.java:68)
	at burp.SettingsTab.<init>(SettingsTab.java:44)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:33)
	at burp.Zx5.ZS(Unknown Source)
	at burp.Zcp_.Zc(Unknown Source)
	at burp.Zcpk.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
a
![image](https://github.com/sleeyax/burp-awesome-tls/assets/73827139/50cb915b-85a6-4178-a175-b7d70e28ed9c)

**Comment by sleeyax** [comment] 2023-12-21 09:47
Duplicate of: #15

**Closed by sleeyax** 2023-12-21 09:47 UTC
