### ISSUE TITLE
Awesome TLS error: create spec from client hello: FingerprintClientHello: unsupported extension 65037

### ISSUE THREAD

**Issue by s3nail1** [sleeyax/burp-awesome-tls#69] opened 2024-05-01 14:02 UTC
Awesome TLS error: create spec from client hello: FingerprintClientHello: unsupported extension 65037

**Comment by s3nail1** [comment] 2024-05-01 14:06
Set the error message returned by hex client hello

**Comment by sleeyax** [comment] 2024-05-01 14:06
Please provide more information to reproduce this issue or no one can help you.

**Comment by s3nail1** [comment] 2024-05-01 14:13
I access https://cloudflare.manfredi.io/ through Chrome and capture the Client Hello through wireshark. I copy its hex value to the Hex Client Hello of the plug-in. Then when I access it through BurpSuite, I will be shown the error message: Awesome TLS error. : create spec from client hello: FingerprintClientHello: unsupported extension 65037

**Comment by sleeyax** [comment] 2024-05-01 14:20
Ah I see. Thanks for reporting. 

65037 is the ECH extension. We probably just need to update UTLS to fix this issue because basic support has landed for that a while ago. In the meantime you should be able to omit the extension to still have a decent, although imperfect, TLS fingerprint.

**Comment by s3nail1** [comment] 2024-05-01 14:24
Oh, okay, thank you

**Closed** 2024-05-01 22:28 UTC

**Comment by sleeyax** [comment] 2024-05-01 22:36
This is resolved in https://github.com/sleeyax/burp-awesome-tls/releases/tag/v1.2.2.
