### ISSUE TITLE
error on burp

### ISSUE THREAD

**Issue by xcypher78** [sleeyax/burp-awesome-tls#40] opened 2023-11-20 01:49 UTC
java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Integer.parseInt(Integer.java:630)
	at java.base/java.lang.Integer.parseInt(Integer.java:784)
	at burp.Settings.getHttpTimeout(Settings.java:68)
	at burp.SettingsTab.<init>(SettingsTab.java:44)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:33)
	at burp.Zcp.Zi(Unknown Source)
	at burp.Zu1y.ZY(Unknown Source)
	at burp.Zu11.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by rank0** [comment] 2023-11-20 03:32
I have encountered the same error.
java version "17.0.8" 2023-07-18 LTS
burpsuite:v2023.2.4 professional
macbook pro

**Comment by sleeyax** [comment] 2023-11-20 12:46
Duplicate of: https://github.com/sleeyax/burp-awesome-tls/issues/15. See the last comment for a temporary solution.

**Closed by sleeyax** 2023-11-20 12:46 UTC
