### ISSUE TITLE
加载插件时报错

### ISSUE THREAD

**Issue by MoSheTeam** [sleeyax/burp-awesome-tls#54] opened 2023-12-27 08:14 UTC
java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Integer.parseInt(Integer.java:630)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at burp.Settings.getHttpTimeout(Settings.java:68)
	at burp.SettingsTab.<init>(SettingsTab.java:44)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:33)
	at burp.Zx5.ZS(Unknown Source)
	at burp.Zcp_.Zc(Unknown Source)
	at burp.Zcpk.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by sleeyax** [comment] 2023-12-27 09:44
Duplicate of #15

**Closed** 2023-12-27 09:44 UTC
