### ISSUE TITLE
Unable to load library on Ubuntu

### ISSUE THREAD

**Issue by adrian-rt** [sleeyax/burp-awesome-tls#31] opened 2023-07-15 13:45 UTC
Hi,

In burp I get an error like "Failed to connect to 127.0.0.1:8888"

the server is not started obviously.

Also, when I unload the extension I get an error like 

```
java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Unable to load library 'server.so':
server.so: cannot open shared object file: No such file or directory
server.so: cannot open shared object file: No such file or directory
Native library (linux-x86-64/server.so) not found in resource path ([file:/tmp/burp9901995054636778576.tmp/32]) [in thread "Thread-19"]
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:301)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:461)
	at com.sun.jna.Library$Handler.<init>(Library.java:192)
	at com.sun.jna.Native.load(Native.java:622)
	at com.sun.jna.Native.load(Native.java:596)
	at burp.ServerLibrary.<clinit>(ServerLibrary.java:8)
	at burp.BurpExtender.lambda$registerExtenderCallbacks$0(BurpExtender.java:36)
	at java.base/java.lang.Thread.run(Thread.java:1589)

```

**Comment by adrian-rt** [comment] 2023-07-15 14:59
I've managed to start the server, but it doesn't work.

I'm detected and get a message like:

`<html><head><title>Request Rejected</title></head><body>The requested URL was rejected. Please consult with your administrator.<br><br>Your support ID is: 16672172601756045050<br><br><a href='javascript:history.back();'>[Go Back]</a></body></html>`

**Comment by sleeyax** [comment] 2023-07-15 17:28
Please provide more details.

- How did you manage to solve your initial issue and start the server?
- What site are you trying to access?

**Comment by adrian-rt** [comment] 2023-07-15 17:35
Sure,

I pointed the Java Enviroment in Burp to the location where I compiled the server.so file.

I can't provide the website in public, but I can say that it is hosting in Azure, so it's not technically Cloudflare or Akamai.

**Comment by sleeyax** [comment] 2023-07-15 18:51
About your initial issue: did you download `Burp-Awesome-TLS-linux-amd64.jar` or `Burp-Awesome-TLS-fat.jar` from the [latest release](https://github.com/sleeyax/burp-awesome-tls/releases/latest)? Only those builds contain the `linux-x86-64/server.so` library you need for your OS and architecture.

And regarding this misterious site that doesn't work on your end, I'll need more details. You can send me a message on Telegram or Discord if you're willing to share the URL in private, otherwise it will be impossible for me to look into it. Either way it's unrelated to this issue.

**Comment by adrian-rt** [comment] 2023-07-16 11:48
@sleeyax ,

It's not just about sharing the URL, I'll need to share the credentials as well and I can't do that (it's a client).

the homepage loads fine, but when I try to login and do a POST that is when I'm detected and blocked.

thanks.

**Comment by sleeyax** [comment] 2023-07-16 12:00
Understandable, but without a reproducible example for me to test you're on your own. You can build this project from source, enable debugging and compare HTTP/TLS requests with real browser traffic to try and see where it goes wrong. Closing this issue because it's going off topic.

**Closed by sleeyax** 2023-07-16 12:00 UTC
Labels: bug
