### ISSUE TITLE
err

### ISSUE THREAD

**Issue by lemonlove7** [sleeyax/burp-awesome-tls#44] opened 2023-11-24 03:55 UTC
java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Integer.parseInt(Integer.java:630)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at burp.Settings.getTimeout(Settings.java:52)
	at burp.SettingsTab.<init>(SettingsTab.java:38)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:33)
	at burp.Zf92.ZK(Unknown Source)
	at burp.Zjpm.ZR(Unknown Source)
	at burp.Zjp7.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by sleeyax** [comment] 2023-11-24 10:43
Duplicate of: #15.

See https://github.com/sleeyax/burp-awesome-tls/issues/15#issuecomment-1575056463

**Closed by sleeyax** 2023-11-24 10:43 UTC
