### ISSUE TITLE
Not working on Windows x64

### ISSUE THREAD

**Issue by misssis1** [sleeyax/burp-awesome-tls#41] opened 2023-11-21 19:06 UTC
Downloaded the extension and added it. After that everything I changed in the screenshot, when I try to open any site it errors.
![1](https://github.com/sleeyax/burp-awesome-tls/assets/151674518/d64567ea-152d-4ea2-b58b-24fc1e854ff6)
![2](https://github.com/sleeyax/burp-awesome-tls/assets/151674518/6239bbd7-043a-4da5-8c1e-eb869d7979cb)
![3](https://github.com/sleeyax/burp-awesome-tls/assets/151674518/ba2a99bd-1bb1-416a-a50c-48ca28c59525)

**Comment by misssis1** [comment] 2023-11-21 19:07
Restarting didn't change anything

**Comment by misssis1** [comment] 2023-11-21 19:17
I also tried the latest versions of 2023, the result is the same

**Comment by misssis1** [comment] 2023-11-22 09:06
@sleeyax

**Comment by sleeyax** [comment] 2023-11-22 09:28
Try to open https://127.0.0.1:8081/ in a regular browser (click accept risk and continue to ignore the self-signed SSL certificate). It should respond with `Awesome TLS error: missing transport configuration`. Then you know the Awesome TLS server is running and it's probably an issue with your burp configuration.

**Comment by sleeyax** [comment] 2023-11-22 09:30
Ah and in your case maybe you forgot to click save settings (at the bottom)? 8081 is a custom port you configured. Maybe restart burp afterwards to be sure.

**Comment by misssis1** [comment] 2023-11-22 11:54
After saving the settings, I clicked and restarted - same result. If I use a normal browser, it doesn't open either: 
![1](https://github.com/sleeyax/burp-awesome-tls/assets/151674518/498152e6-8c80-4dac-81fe-e176b1c40fa2)

**Comment by misssis1** [comment] 2023-11-22 11:56
If I understand correctly, the Awesome Tls server won't start? What can be done about it? On another computer the problem is the same...

**Comment by sleeyax** [comment] 2023-11-22 11:57
Looks like it... Check the extension error log and paste it here if you see anything. Also try a different port like 8887 to be sure.

**Comment by misssis1** [comment] 2023-11-22 12:05
Tried changing ports - same result.

**Comment by misssis1** [comment] 2023-11-22 12:07
I didn't need to install any additional software? It was enough to download Burp from the official site (.exe) and your extension and add it, is that correct? Again, the problem is the same on the second computer

**Comment by misssis1** [comment] 2023-11-22 14:32
Another question. I have Windows 10 Pro 22H2. The extension only installs this correctly: 
![1](https://github.com/sleeyax/burp-awesome-tls/assets/151674518/220772e3-724f-4af9-a697-552a25fb867a)

**Comment by misssis1** [comment] 2023-11-22 14:34
If I add Burp-Awesome-TLS-fat.jar or Burp-Awesome-TLS-windows-amd64.jar, burp immediately crashes. Although as far as I understand I need to install these versions?

**Comment by sleeyax** [comment] 2023-11-22 16:41
Hmm can you share a screenshot of Settings app > System > About > Device specifications (I only need to know System Type). 

If it looks like this you should be able to run the `amd64` build:

<img width="370" alt="image" src="https://github.com/sleeyax/burp-awesome-tls/assets/30344294/b65e0634-6917-4ab0-955c-26e88883245d">

`i386` is for 32-bit architectures, which is rather uncommon nowadays. 

That being said, I tried to load the `i386` build in my Windows VM and finally manged to reproduce the issue you're having :) I suspect that Burps Java runtime tries to load the x64 binary for the server according to your system's architecture, but can't find it and then doesn't do anything. You still see logs in the output log because those are logged from the Java side, but nothing is actually sent to the go side (server) because the server just isn't running.

So, there's actually 2 'issues' to conclude from this:
- We need to figure out why the 64-bit build doesn't work for you
- An error should be logged when the server binary isn't found to prevent confusion like this in the future

**Comment by sleeyax** [comment] 2023-11-22 16:50
I created an issue for the latter (feel free to contribute a solution if you want, I'd highly appreciate it!). Let's stick to the former problem in this issue.

**Comment by misssis1** [comment] 2023-11-22 18:37
> Хм, не могли бы вы поделиться снимком экрана приложения «Настройки» > «Система» > «О программе» > «Характеристики устройства» (мне нужно только знать тип системы).
> 
> Если это выглядит так, вы сможете запустить `amd64`строить:
> <img alt="изображение" width="370" src="https://user-images.githubusercontent.com/30344294/284973576-b65e0634-6917-4ab0-955c-26e88883245d.png">
> 
> `i386`предназначен для 32-битных архитектур, что в настоящее время довольно редко.
> 
> That being said, I tried to load the `i386` build in my Windows VM and finally manged to reproduce the issue you're having :) I suspect that Burps Java runtime tries to load the x64 binary for the server according to your system's architecture, but can't find it and then doesn't do anything. You still see logs in the output log because those are logged from the Java side, but nothing is actually sent to the go side (server) because the server just isn't running.
> 
> So, there's actually 2 'issues' to conclude from this:
> 
>     * We need to figure out why the 64-bit build doesn't work for you
> 
>     * An error should be logged when the server binary isn't found to prevent confusion like this in the future



> Hmm can you share a screenshot of Settings app > System > About > Device specifications (I only need to know System Type).
> 
> If it looks like this you should be able to run the `amd64` build:
> <img alt="image" width="370" src="https://user-images.githubusercontent.com/30344294/284973576-b65e0634-6917-4ab0-955c-26e88883245d.png">
> 
> `i386` is for 32-bit architectures, which is rather uncommon nowadays.
> 
> That being said, I tried to load the `i386` build in my Windows VM and finally manged to reproduce the issue you're having :) I suspect that Burps Java runtime tries to load the x64 binary for the server according to your system's architecture, but can't find it and then doesn't do anything. You still see logs in the output log because those are logged from the Java side, but nothing is actually sent to the go side (server) because the server just isn't running.
> 
> So, there's actually 2 'issues' to conclude from this:
> 
>     * We need to figure out why the 64-bit build doesn't work for you
> 
>     * An error should be logged when the server binary isn't found to prevent confusion like this in the future

![1](https://github.com/sleeyax/burp-awesome-tls/assets/151674518/cb85f5c8-1e9f-485d-9503-d97f1716e1f3)

**Comment by misssis1** [comment] 2023-11-22 18:44
1. Installed the latest version of Burp Community Edition
2. Downloaded the Burp-Awesome-TLS-windows-amd64.jar extension
3. Didn't change any settings at all, added the plugin - it added, but the errors stated the following:

java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Integer.parseInt(Integer.java:627)
	at java.base/java.lang.Integer.parseInt(Integer.java:781)
	at burp.Settings.getHttpTimeout(Settings.java:68)
	at burp.SettingsTab.<init>(SettingsTab.java:44)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:33)
	at burp.Zprt.Zw(Unknown Source)
	at burp.Zyup.Zk(Unknown Source)
	at burp.Zyut.lambda$initializeOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)

4. I restart Burp - the plugin is not active! I add it again, Burp crashes immediately after adding it.
5. Contents of the application log during Burp crash:
![2](https://github.com/sleeyax/burp-awesome-tls/assets/151674518/570d5381-1e24-4872-9b9a-b974264af22a)

**Comment by misssis1** [comment] 2023-11-22 18:44
> 1. Installed the latest version of Burp Community Edition
> 
>     2. Downloaded the Burp-Awesome-TLS-windows-amd64.jar extension
> 
>     3. Didn't change any settings at all, added the plugin - it added, but the errors stated the following:
> 
> 
> java.lang.NumberFormatException: Cannot parse null string at java.base/java.lang.Integer.parseInt(Integer.java:627) at java.base/java.lang.Integer.parseInt(Integer.java:781) at burp.Settings.getHttpTimeout(Settings.java:68) at burp.SettingsTab.(SettingsTab.java:44) at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:33) at burp.Zprt.Zw(Unknown Source) at burp.Zyup.Zk(Unknown Source) at burp.Zyut.lambda$initializeOnNewThread$0(Unknown Source) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) at java.base/java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) at java.base/java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) at java.base/java.lang.Thread.run(Thread.java:1623)
> 
>     4. I restart Burp - the plugin is not active! I add it again, Burp crashes immediately after adding it.
> 
>     5. Contents of the application log during Burp crash:
>        ![2](https://user-images.githubusercontent.com/151674518/285011290-570d5381-1e24-4872-9b9a-b974264af22a.png)

Before all these actions was restored win 10 image on which Burp was never installed

**Comment by misssis1** [comment] 2023-11-22 19:08
> 1. Установлена ​​последняя версия Burp Community Edition.
> 
>     2. Скачал расширение Burp-Awesome-TLS-windows-amd64.jar.
> 
>     3. Никаких настроек вообще не менял, добавил плагин - добавилось, но ошибки выдавали следующее:
> 
> 
> java.lang.NumberFormatException: невозможно проанализировать нулевую строку в java.base/java.lang.Integer.parseInt(Integer.java:627) в java.base/java.lang.Integer.parseInt(Integer.java:781) в burp.Settings.getHttpTimeout(Settings.java:68) в Burp.SettingsTab.(SettingsTab.java:44) в burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:33) в burp.Zprt.Zw (неизвестный источник) в burp.Zyup.Zk (неизвестный источник) в burp.Zyut.lambda$initializeOnNewThread$0 (неизвестный источник) в java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) в java.base/java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) в java.base/java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) в java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) в java.base/java.lang.Thread.run(Thread.java:1623)
> 
>     4. Перезапускаю Burp - плагин не активен!  Добавляю еще раз, Burp вылетает сразу после добавления.
> 
>     5. Содержимое журнала приложения во время сбоя Burp: 
>        ![2](https://user-images.githubusercontent.com/151674518/285011290-570d5381-1e24-4872-9b9a-b974264af22a.png)



> 1. Installed the latest version of Burp Community Edition
> 
>     2. Downloaded the Burp-Awesome-TLS-windows-amd64.jar extension
> 
>     3. Didn't change any settings at all, added the plugin - it added, but the errors stated the following:
> 
> 
> java.lang.NumberFormatException: Cannot parse null string at java.base/java.lang.Integer.parseInt(Integer.java:627) at java.base/java.lang.Integer.parseInt(Integer.java:781) at burp.Settings.getHttpTimeout(Settings.java:68) at burp.SettingsTab.(SettingsTab.java:44) at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:33) at burp.Zprt.Zw(Unknown Source) at burp.Zyup.Zk(Unknown Source) at burp.Zyut.lambda$initializeOnNewThread$0(Unknown Source) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) at java.base/java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) at java.base/java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) at java.base/java.lang.Thread.run(Thread.java:1623)
> 
>     4. I restart Burp - the plugin is not active! I add it again, Burp crashes immediately after adding it.
> 
>     5. Contents of the application log during Burp crash:
>        ![2](https://user-images.githubusercontent.com/151674518/285011290-570d5381-1e24-4872-9b9a-b974264af22a.png)

**5 para, text:**
Faulting application name: BurpSuiteCommunity.exe, version: 2023.10.3.6, time stamp: 0x647f32a9
Faulting module name: jna715638035215112812.dll, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0x80000003
Fault offset: 0x0000000000066541
Faulting process id: 0x53c
Faulting application start time: 0x01da1d74ebcdc148
Faulting application path: C:\Program Files\BurpSuiteCommunity\BurpSuiteCommunity.exe
Faulting module path: C:\Users\user\AppData\Local\Temp\jna-3599307\jna715638035215112812.dll
Report Id: b94e2b58-f413-4015-a364-2d220f5486cb
Faulting package full name: 
Faulting package-relative application ID:

**Comment by sleeyax** [comment] 2023-11-22 19:53
Hmm I'm running out of ideas here :thinking:. We're both running the same architecture for the VM but on your end something goes wrong with Burps JNA (Java Native Access), presumably when it tries to resolve the bundled server dll. 

Maybe you can figure out more by compiling the jar manually from source? And perhaps slightly modify the Java source to add some log statements around the parts that load the server dll? Compilation instructions are at the bottom of the README. Unfortunately I can't do this myself as I can't reproduce this issue on any of my machines.

**Comment by misssis1** [comment] 2023-11-22 20:35
> Hmm I'm running out of ideas here 🤔. We're both running the same architecture for the VM but on your end something goes wrong with Burps JNA (Java Native Access), presumably when it tries to resolve the bundled server dll.
> 
> Maybe you can figure out more by compiling the jar manually from source? And perhaps slightly modify the Java source to add some log statements around the parts that load the server dll? Compilation instructions are at the bottom of the README. Unfortunately I can't do this myself as I can't reproduce this issue on any of my machines.

Unfortunately, I can't get through this manual

**Comment by misssis1** [comment] 2023-11-22 20:36
In a virtual machine on win 7 everything works successfully, I will probably reinstall the windows 10 build

**Comment by sleeyax** [comment] 2023-11-22 22:22
Ok, let me know how it goes!

**Comment by sleeyax** [comment] 2023-11-22 22:25
And if you need help with building from source let me know. You can also [message me on social media](https://github.com/sleeyax#wave-socials) (preferably discord or telegram) if that's easier. But if you have no experience in coding I must admit it will be difficult to help you.

**Comment by misssis1** [comment] 2023-11-26 19:43
I figured out the reason why the plugin wasn't working for me. And so: 
Was installed Windows 10 on a virtual machine - no problems, the plugin works as it should! The same Windows is installed on a physical machine:
Gigabyte Z77 DS3h motherboard rev. 1.0
GTX 1080TI EVGA graphics card
On the freshly installed Windows, only the chipset and NVIDIA drivers were installed. I do all the same as described above - the program closes the error in the log is the same. I uninstall the NVIDIA driver - everything works at once! As a result, the NVIDIA driver was installed from the Windows Update Center, with this scheme everything works. Conclusion: installing NVIDIA driver for GTX 1080TI EVGA from the official site - we get a plugin that doesn't work - in my case when adding the Burp plugin there was a failure! Solution: install the driver through Windows Update Center. Link to the driver with which the plugin did not work for me: 
https://www.nvidia.com/ru-ru/geforce/drivers/results/216428/

**Comment by misssis1** [comment] 2023-11-26 19:57
And so the last thing I did, restored the Windows 10 image (from the first post) uninstalled the NVIDIA driver and installed it through the Windows Update Center, after that I got it working!!!!

**Comment by sleeyax** [comment] 2023-11-27 21:51
Closing as a solution has been found.

**Closed by sleeyax** 2023-11-27 21:51 UTC
Labels: support

**Comment by sleeyax** [comment] 2024-01-10 11:27
> Wanted to add this issue isn't a one off and I get the same exact crash with an MSI GTX 1080 Ti using the 64 bit jar file

Have you tried fixing it in a similar way to the other user? If that doesn't work I'll need more details about your system because I can't reproduce this. Alternatively, try to build the extension from source and see what that does for you.
